# Generated by Django 5.2.1 on 2025-05-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csr',
            name='nature_of_petition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
