# Generated by Django 5.2.1 on 2025-06-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0002_csr_transfered_to_alter_csr_police_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='PS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='arrestofslfishermen',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='arrestoftnfishermen',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='attackontnfishermen',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='atvpatrol',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='beatdetails',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='bnssmissingcase',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='boatpatrol',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='maritimeact',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='onroadvehiclestatus',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='onwatervehiclestatus',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='othercases',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='rescueatbeach',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='rescueatsea',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='vehiclecheckothers',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='vehiclecheckpost',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
        migrations.AlterField(
            model_name='vvcmeeting',
            name='mps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.mps'),
        ),
    ]
