# Generated by Django 5.2.1 on 2025-06-30 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0003_ps_alter_arrestofslfishermen_mps_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrestofslfishermen',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.ps'),
        ),
        migrations.AddField(
            model_name='attackontnfishermen',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.ps'),
        ),
        migrations.AddField(
            model_name='bnssmissingcase',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.ps'),
        ),
        migrations.AddField(
            model_name='maritimeact',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.ps'),
        ),
        migrations.AddField(
            model_name='othercases',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.ps'),
        ),
        migrations.AddField(
            model_name='rescueatbeach',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.ps'),
        ),
        migrations.AddField(
            model_name='seizure',
            name='ps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.ps'),
        ),
        migrations.AlterField(
            model_name='arrestofslfishermen',
            name='arrested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsr.other_agencies'),
        ),
        migrations.AlterField(
            model_name='arrestoftnfishermen',
            name='arrested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsr.other_agencies'),
        ),
        migrations.AlterField(
            model_name='attackontnfishermen',
            name='attacked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsr.other_agencies'),
        ),
        migrations.AlterField(
            model_name='csr',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.ps'),
        ),
    ]
