# Generated by Django 5.2.1 on 2025-05-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0003_alter_csr_nature_of_petition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bnssmissingcase',
            old_name='deceased',
            new_name='diseased',
        ),
    ]
