# Generated by Django 5.2.1 on 2025-05-30 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0004_rename_deceased_bnssmissingcase_diseased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnssmissingcase',
            name='date_of_occurrence',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bnssmissingcase',
            name='date_of_receipt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
