# Generated by Django 5.2.1 on 2025-07-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0004_arrestofslfishermen_transfered_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rescueatbeach',
            old_name='transfered_to',
            new_name='police_station',
        ),
        migrations.AlterField(
            model_name='bnssmissingcase',
            name='police_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bnss_police_station_cases', to='dsr.ps'),
        ),
        migrations.AlterField(
            model_name='bnssmissingcase',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnss_transfered_cases', to='dsr.ps'),
        ),
        migrations.AlterField(
            model_name='maritimeact',
            name='police_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maritime_police_station_cases', to='dsr.ps'),
        ),
        migrations.AlterField(
            model_name='maritimeact',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maritime_transfered_cases', to='dsr.ps'),
        ),
        migrations.AlterField(
            model_name='othercases',
            name='police_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='othercases_police_station_cases', to='dsr.ps'),
        ),
        migrations.AlterField(
            model_name='othercases',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='othercases_transfered_cases', to='dsr.ps'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='handed_over_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
