# Generated by Django 5.2.1 on 2025-07-01 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0005_rename_transfered_to_rescueatbeach_police_station_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrestofslfishermen',
            old_name='police_station',
            new_name='ps_limit',
        ),
        migrations.RenameField(
            model_name='rescueatbeach',
            old_name='police_station',
            new_name='ps_limit',
        ),
        migrations.RemoveField(
            model_name='arrestofslfishermen',
            name='transfered_to',
        ),
        migrations.RemoveField(
            model_name='bnssmissingcase',
            name='police_station',
        ),
        migrations.RemoveField(
            model_name='maritimeact',
            name='police_station',
        ),
        migrations.RemoveField(
            model_name='onroadvehiclestatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='onwatervehiclestatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='othercases',
            name='police_station',
        ),
        migrations.AddField(
            model_name='arrestoftnfishermen',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='arrestoftnfishermen',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bnssmissingcase',
            name='ps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.ps'),
        ),
        migrations.AddField(
            model_name='maritimeact',
            name='ps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.ps'),
        ),
        migrations.AddField(
            model_name='othercases',
            name='ps_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.ps'),
        ),
        migrations.AlterField(
            model_name='beatdetails',
            name='day_beat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beatdetails',
            name='night_beat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bnssmissingcase',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.other_agencies'),
        ),
        migrations.AlterField(
            model_name='maritimeact',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.other_agencies'),
        ),
        migrations.AlterField(
            model_name='othercases',
            name='transfered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.other_agencies'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='awareness_programs_conducted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='boat_guard_checked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='check_post_checked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='coastal_security_exercises_conducted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='meetings_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='mps_visited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='villages_visited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='vvc_meeting_conducted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='handed_over_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.other_agencies'),
        ),
    ]
