# Generated by Django 5.2.1 on 2025-06-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0005_alter_bnssmissingcase_date_of_occurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnssmissingcase',
            name='io',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
