# Generated by Django 5.2.1 on 2025-07-01 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0006_rename_police_station_arrestofslfishermen_ps_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csr',
            old_name='police_station',
            new_name='mps_limit',
        ),
        migrations.RemoveField(
            model_name='csr',
            name='transfered_to',
        ),
        migrations.AddField(
            model_name='csr',
            name='io',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsr.officer'),
        ),
    ]
