# Generated by Django 5.2.1 on 2025-07-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0007_rename_police_station_csr_mps_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrestoftnfishermen',
            name='district',
            field=models.CharField(blank=True, choices=[('Chennai', 'Chennai'), ('Chengalpattu', 'Chengalpattu'), ('Villupuram', 'Villupuram'), ('Rameswaram', 'Rameswaram'), ('Cuddalore', 'Cuddalore')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attackontnfishermen',
            name='district',
            field=models.CharField(blank=True, choices=[('Chennai', 'Chennai'), ('Chengalpattu', 'Chengalpattu'), ('Villupuram', 'Villupuram'), ('Rameswaram', 'Rameswaram'), ('Cuddalore', 'Cuddalore')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rescueatsea',
            name='number_of_boats_rescued',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
