# Generated by Django 5.2.1 on 2025-07-08 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0008_arrestoftnfishermen_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatpatrol',
            name='boat_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsr.onwatervehiclestatus'),
        ),
    ]
