# Generated by Django 5.2.1 on 2025-07-08 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0009_alter_boatpatrol_boat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atvpatrol',
            name='atv_number',
            field=models.ForeignKey(blank=True, limit_choices_to={'vehicle_type': 'ATV'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atv_patrols', to='dsr.onroadvehiclestatus'),
        ),
    ]
