# Generated by Django 5.2.1 on 2025-07-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0010_alter_atvpatrol_atv_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onroadvehiclestatus',
            name='vehicle_type',
            field=models.CharField(choices=[('TWO_WHEELER', 'Two Wheeler'), ('FOUR_WHEELER', 'Four Wheeler'), ('ATV', 'ATV')], max_length=20),
        ),
    ]
