# Generated by Django 5.2.1 on 2025-07-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0011_alter_onroadvehiclestatus_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsr.officer'),
        ),
    ]
