# Generated by Django 5.2.1 on 2025-06-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0012_arrestofslfishermen_choices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
