# Generated by Django 5.2.1 on 2025-07-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0012_proforma_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='onroadvehiclestatus',
            name='alloted_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
