# Generated by Django 5.2.1 on 2025-07-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0013_onroadvehiclestatus_alloted_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onroadvehiclestatus',
            name='alloted_to',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
