# Generated by Django 5.2.1 on 2025-08-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0014_alter_onroadvehiclestatus_alloted_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='mps',
            name='range',
            field=models.CharField(blank=True, choices=[('Nagapattinam', 'Nagapattinam'), ('Rameswaram', 'Rameswaram')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mps',
            name='unit',
            field=models.CharField(blank=True, choices=[('Chennai', 'Chennai'), ('Mahabalipuram ', 'Mahabalipuram'), ('Cuddalore', 'Cuddalore'), ('Nagapattinam', 'Nagapattinam'), ('Vedaraniyam', 'Vedaraniyam'), ('Pattukkottai', 'Pattukkottai'), ('Muthupettai ', 'Muthupettai'), ('Rameswaram', 'Rameswaram'), ('Tuticorin', 'Tuticorin'), ('Kanyakumari', 'Kanyakumari')], max_length=20, null=True),
        ),
    ]
